# Generated by Django 5.1.15 on 2026-08-29 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('okul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('name', models.CharField(db_index=True, help_text="Örn. 'D-204', 'Fen Laboratuvarı'.", max_length=80, verbose_name='salon adı')),
                ('block', models.CharField(blank=True, default='', help_text="Serbest konum bilgisi (örn. 'A Blok 2. Kat').", max_length=80, verbose_name='blok / kat')),
                ('layout_plan', models.JSONField(blank=True, default=dict, help_text='2D plan: grid + sıralar (tekli/ikili/üçlü) + mobilya. Şema layout.validate_layout_plan ile doğrulanır.', verbose_name='yerleşim planı')),
                ('numbering_scheme', models.CharField(choices=[('S_PATTERN', 'S düzeni'), ('STRAIGHT', 'Düz')], default='S_PATTERN', max_length=10, verbose_name='numaralandırma')),
                ('is_active', models.BooleanField(default=True, help_text='Pasif salon yeni oturum planlamasında seçilemez; kayıt silinmez.', verbose_name='aktif')),
                ('linked_section', models.ForeignKey(blank=True, help_text='Salon bir şubenin dersliğiyse o şube (klasik düzen eşlemesi).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_rooms', to='okul.classsection', verbose_name='bağlı şube')),
            ],
            options={
                'verbose_name': 'sınav salonu',
                'verbose_name_plural': 'sınav salonları',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uq_examroom_name_alive')],
            },
        ),
    ]
