# Generated by Django 5.1.15 on 2026-08-29 16:32

import django.db.models.deletion
import shared.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0001_initial'),
        ('okul', '0001_initial'),
        ('sinav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('name', models.CharField(max_length=120, verbose_name='oturum adı')),
                ('exam_date', models.DateField(db_index=True, verbose_name='sınav tarihi')),
                ('start_time', models.TimeField(verbose_name='başlangıç saati')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=40, help_text='Oturumun varsayılan süresi (40 dk); ders bazlı süre ezilebilir.', verbose_name='süre (dk)')),
                ('session_type', models.CharField(choices=[('SCHOOL', 'Okul'), ('DISTRICT', 'İlçe'), ('PROVINCE', 'İl'), ('NATIONAL', 'Ülke')], default='SCHOOL', max_length=10, verbose_name='tür')),
                ('layout_mode', models.CharField(choices=[('BUTTERFLY', 'Kelebek'), ('HOME_CLASSROOM', 'Kendi dersliğinde')], default='BUTTERFLY', max_length=14, verbose_name='düzen')),
                ('proctors_enabled', models.BooleanField(default=False, help_text='U2 — varsayılan kapalı.', verbose_name='gözetmen modülü')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('DISTRIBUTED', 'Dağıtıldı'), ('APPROVED', 'Onaylandı'), ('ARCHIVED', 'Arşiv')], db_index=True, default='DRAFT', max_length=12, verbose_name='durum')),
                ('distribution_params', models.JSONField(blank=True, default=dict, help_text="Seed, mod ve opsiyonlar (dağıtım motoru yazar; seed R8'de basılır).", verbose_name='dağıtım parametreleri')),
                ('transfer_check_confirmed_by_name', models.CharField(blank=True, default='', max_length=128, verbose_name='nakil kontrolünü onaylayan')),
                ('transfer_check_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='nakil kontrolü onay zamanı')),
                ('approved_by_name', models.CharField(blank=True, default='', max_length=128, verbose_name='onaylayan')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='onay zamanı')),
                ('anonymized_at', models.DateTimeField(blank=True, null=True, verbose_name='anonimleştirme zamanı')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='okul.schoolterm', verbose_name='dönem')),
            ],
            options={
                'verbose_name': 'sınav oturumu',
                'verbose_name_plural': 'sınav oturumları',
                'ordering': ['-exam_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('full_name', shared.crypto.EncryptedCharField(max_length=150, verbose_name='ad soyad (snapshot)')),
                ('student_number', models.CharField(max_length=20, verbose_name='okul no (snapshot)')),
                ('class_label', models.CharField(max_length=12, verbose_name='sınıf/şube (snapshot)')),
                ('seat_no', models.PositiveSmallIntegerField(verbose_name='koltuk no')),
                ('excuse_status', models.CharField(choices=[('PENDING', 'Beklemede'), ('EXCUSED', 'Özürlü'), ('UNEXCUSED', 'Özürsüz')], db_index=True, default='PENDING', max_length=10, verbose_name='mazeret durumu')),
                ('note', models.TextField(blank=True, default='', help_text="Belge no/tarih gibi serbest metin (örn. 'Rapor no 123, 10.06.2026'). SAĞLIK TANISI YAZMAYIN — KVKK Madde 6 özel nitelikli veridir.", verbose_name='açıklama')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='sinav.examroom', verbose_name='salon')),
                ('student', models.ForeignKey(blank=True, help_text='Anonimleştirilmiş arşivde boş (F27).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_attendance_records', to='okul.student', verbose_name='öğrenci')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='sinav.examsession', verbose_name='oturum')),
            ],
            options={
                'verbose_name': 'sınav yoklama kaydı',
                'verbose_name_plural': 'sınav yoklama kayıtları',
                'ordering': ['room_id', 'seat_no'],
                'indexes': [models.Index(fields=['session', 'room'], name='sinav_attend_sess_room_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('session', 'student'), name='uq_examattendance_session_student_alive')],
            },
        ),
        migrations.CreateModel(
            name='ExamSessionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Boş = oturum süresi.', null=True, verbose_name='süre (dk)')),
                ('participant_type', models.CharField(choices=[('LEVEL', 'Seviye geneli'), ('SECTIONS', 'Şube şube')], max_length=10, verbose_name='katılımcı tipi')),
                ('level', models.PositiveSmallIntegerField(blank=True, help_text='Satırın tek seviyesi (0 = Hazırlık). Servis katmanı zorunlu kılar.', null=True, verbose_name='seviye')),
                ('section_ids', models.JSONField(blank=True, default=list, help_text='SECTIONS tipi için okul.ClassSection id.', verbose_name="şube id'leri")),
                ('shared_booklet', models.BooleanField(default=False, help_text='Karma seviyeler tek kitapçık/tek çakışma grubu.', verbose_name='ortak kitapçık')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_courses', to='dersler.course', verbose_name='ders')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='sinav.examsession', verbose_name='oturum')),
            ],
            options={
                'verbose_name': 'oturum dersi',
                'verbose_name_plural': 'oturum dersleri',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('session', 'course', 'level'), name='uq_examsessioncourse_level_alive')],
            },
        ),
        migrations.CreateModel(
            name='ExamSessionRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Dağıtım/paketleme salon sırası.', verbose_name='kullanım sırası')),
                ('capacity_override', models.PositiveSmallIntegerField(blank=True, help_text='Boş = plandan hesaplanan kapasite.', null=True, verbose_name='kapasite sınırı')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_rooms', to='sinav.examroom', verbose_name='salon')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='sinav.examsession', verbose_name='oturum')),
            ],
            options={
                'verbose_name': 'oturum salonu',
                'verbose_name_plural': 'oturum salonları',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('session', 'room'), name='uq_examsessionroom_alive')],
            },
        ),
        migrations.CreateModel(
            name='PlacementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('scope', models.CharField(choices=[('SESSION', 'Oturum'), ('PERMANENT', 'Kalıcı')], default='PERMANENT', max_length=10, verbose_name='kapsam')),
                ('rule_type', models.CharField(choices=[('HOME_CLASSROOM', 'Kendi dersliğinde'), ('FIXED_ROOM', 'Belirli salon'), ('FRONT_ROW', 'Ön sıra'), ('SEPARATE_ROOM', 'Ayrı salon')], max_length=14, verbose_name='kural tipi')),
                ('reason_category', models.CharField(choices=[('DISABILITY', 'Engel durumu'), ('IEP', 'BEP'), ('HEALTH', 'Sağlık'), ('OTHER', 'Diğer')], default='OTHER', max_length=10, verbose_name='gerekçe kategorisi')),
                ('session', models.ForeignKey(blank=True, help_text='Yalnız SESSION kapsamında dolu.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_rules', to='sinav.examsession', verbose_name='oturum')),
                ('student', models.ForeignKey(blank=True, help_text='Anonimleştirilmiş arşivin oturum-kurallarında boş (F27).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_placement_rules', to='okul.student', verbose_name='öğrenci')),
                ('target_room', models.ForeignKey(blank=True, help_text='BELIRLI_SALON / AYRI_SALON için zorunlu.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placement_rules', to='sinav.examroom', verbose_name='hedef salon')),
            ],
            options={
                'verbose_name': 'yerleştirme kuralı',
                'verbose_name_plural': 'yerleştirme kuralları',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('session__isnull', True)), fields=('student',), name='uq_placementrule_permanent_alive'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('session__isnull', False)), fields=('student', 'session'), name='uq_placementrule_session_alive')],
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('full_name', shared.crypto.EncryptedCharField(max_length=150, verbose_name='ad soyad (snapshot)')),
                ('student_number', models.CharField(max_length=20, verbose_name='okul no (snapshot)')),
                ('class_label', models.CharField(max_length=12, verbose_name='sınıf/şube (snapshot)')),
                ('desk_row', models.PositiveSmallIntegerField(verbose_name='sıra satırı')),
                ('desk_col', models.PositiveSmallIntegerField(verbose_name='sıra sütunu')),
                ('slot', models.PositiveSmallIntegerField(verbose_name='sıra içi pozisyon')),
                ('seat_no', models.PositiveSmallIntegerField(verbose_name='koltuk no')),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('PINNED', 'Sabit'), ('MANUAL', 'Elle taşındı')], default='NORMAL', max_length=8, verbose_name='durum')),
                ('conflict_group', models.CharField(help_text="Motor anahtarı: '<course_id>:<level>' veya '<course_id>:*'.", max_length=24, verbose_name='çakışma grubu')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_assignments', to='sinav.examroom', verbose_name='salon')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='sinav.examsession', verbose_name='oturum')),
                ('student', models.ForeignKey(blank=True, help_text='Anonimleştirilmiş arşivde boş (F27) — canlı yerleşimde her zaman dolu.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_seat_assignments', to='okul.student', verbose_name='öğrenci')),
            ],
            options={
                'verbose_name': 'yerleşim',
                'verbose_name_plural': 'yerleşimler',
                'ordering': ['room_id', 'seat_no'],
                'indexes': [models.Index(fields=['session', 'room'], name='sinav_seat_session_room_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('session', 'room', 'seat_no'), name='uq_seat_session_room_seat_alive'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('session', 'student'), name='uq_seat_session_student_alive')],
            },
        ),
    ]
