# Generated by Django 5.1.15 on 2026-08-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0002_examsession_examattendancerecord_examsessioncourse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookletRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('IN_PROGRESS', 'Üretiliyor'), ('COMPLETED', 'Tamamlandı'), ('FAILED', 'Başarısız')], db_index=True, default='PENDING', max_length=12, verbose_name='durum')),
                ('file', models.FileField(blank=True, upload_to='exam_booklets/%Y/%m/', verbose_name='ZIP')),
                ('backup_copies', models.PositiveSmallIntegerField(default=0, help_text='Salon başına isimsiz kitapçık adedi.', verbose_name='isimsiz yedek kopya')),
                ('manifest', models.JSONField(blank=True, default=dict, help_text='Salon → dosya adı/kitapçık/sayfa sayıları (PII yok).', verbose_name='manifest')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='hata')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='tamamlanma')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklet_runs', to='sinav.examsession', verbose_name='oturum')),
            ],
            options={
                'verbose_name': 'kitapçık koşusu',
                'verbose_name_plural': 'kitapçık koşuları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('file', models.FileField(upload_to='exam_questions/%Y/%m/', verbose_name="soru PDF'i")),
                ('page_count', models.PositiveSmallIntegerField(verbose_name='sayfa sayısı')),
                ('sha256', models.CharField(max_length=64, verbose_name='içerik özeti')),
                ('score_mode', models.CharField(choices=[('SINGLE_BOX', 'Tek puan kutusu'), ('QUESTION_TABLE', 'Soru bazlı puan tablosu')], default='SINGLE_BOX', max_length=14, verbose_name='puan bölümü')),
                ('question_count', models.PositiveSmallIntegerField(blank=True, help_text='Puan tablosu için (K5).', null=True, verbose_name='soru sayısı')),
                ('session_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_documents', to='sinav.examsessioncourse', verbose_name='oturum dersi')),
            ],
            options={
                'verbose_name': 'soru dosyası',
                'verbose_name_plural': 'soru dosyaları',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('session_course',), name='uq_questiondoc_sessioncourse_alive')],
            },
        ),
    ]
