# Generated by Django 5.1.15 on 2026-08-29 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0001_initial'),
        ('okul', '0002_schoolconfig_bell_schedule'),
        ('sinav', '0003_bookletrun_questiondocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('round', models.PositiveSmallIntegerField(help_text='Dönem içi kaçıncı ortak sınav (1-3; 3 = haftalık ≥6 saatlik derste).', verbose_name='sınav turu')),
                ('name', models.CharField(help_text="Otomatik '1. Dönem 1. Sınav Takvimi'; düzenlenebilir.", max_length=120, verbose_name='takvim adı')),
                ('start_date', models.DateField(verbose_name='başlangıç tarihi')),
                ('end_date', models.DateField(verbose_name='bitiş tarihi')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('SUBMITTED', 'Onaya Sunuldu'), ('APPROVED', 'Onaylandı')], db_index=True, default='DRAFT', max_length=12, verbose_name='durum')),
                ('description_text', models.TextField(blank=True, default='', help_text="Takvim ile imza bloğu arasındaki açıklamalar (mazeret, 'G', vb.).", verbose_name='açıklama metni')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='onaya sunulma zamanı')),
                ('approved_by_name', models.CharField(blank=True, default='', max_length=128, verbose_name='onaylayan (ad-snapshot)')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='onay zamanı')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_calendars', to='okul.schoolterm', verbose_name='dönem')),
            ],
            options={
                'verbose_name': 'sınav takvimi',
                'verbose_name_plural': 'sınav takvimleri',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('level', models.PositiveSmallIntegerField(help_text='Sınıf düzeyi (0=Hazırlık, 9-12).', verbose_name='seviye')),
                ('exam_kind', models.CharField(choices=[('WRITTEN', 'Yazılı'), ('PRACTICE', 'Uygulama')], default='WRITTEN', max_length=10, verbose_name='sınav türü')),
                ('is_butterfly', models.BooleanField(default=True, help_text='False = kendi sınıfında (Kelebek Değil).', verbose_name='kelebek')),
                ('placed_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='yerleştirme tarihi')),
                ('period_no', models.PositiveSmallIntegerField(blank=True, help_text='Ders saati listesindeki saat no (B6).', null=True, verbose_name='ders saati')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='not')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sinav.examcalendar', verbose_name='takvim')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_calendar_entries', to='dersler.course', verbose_name='ders')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_entries', to='sinav.examsession', verbose_name='üretilen oturum')),
            ],
            options={
                'verbose_name': 'sınav takvimi girdisi',
                'verbose_name_plural': 'sınav takvimi girdileri',
            },
        ),
        migrations.CreateModel(
            name='ExamTrackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('name', models.CharField(max_length=160, verbose_name='kalem adı')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='açıklama')),
            ],
            options={
                'verbose_name': 'sınav süreç kalemi',
                'verbose_name_plural': 'sınav süreç kalemleri',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uq_examtrackitem_name_alive')],
            },
        ),
        migrations.CreateModel(
            name='ExamTrackMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('status', models.CharField(choices=[('DONE', 'Yapıldı'), ('NOT_APPLICABLE', 'Kapsam dışı')], max_length=16, verbose_name='durum')),
                ('marked_by_name', models.CharField(blank=True, default='', max_length=128, verbose_name='işaretleyen (ad-snapshot)')),
                ('marked_at', models.DateTimeField(verbose_name='işaret zamanı')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='not')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_marks', to='sinav.examcalendarentry', verbose_name='takvim girdisi')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='sinav.examtrackitem', verbose_name='kalem')),
            ],
            options={
                'verbose_name': 'sınav süreç işareti',
                'verbose_name_plural': 'sınav süreç işaretleri',
            },
        ),
        migrations.AddConstraint(
            model_name='examcalendar',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('semester', 'round'), name='uq_examcalendar_sem_round_alive'),
        ),
        migrations.AddConstraint(
            model_name='examcalendar',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='ck_examcalendar_date_range'),
        ),
        migrations.AddIndex(
            model_name='examcalendarentry',
            index=models.Index(fields=['calendar', 'placed_date'], name='sinav_calentry_cal_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='examcalendarentry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('calendar', 'course', 'level', 'exam_kind'), name='uq_examcalentry_alive'),
        ),
        migrations.AddConstraint(
            model_name='examcalendarentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('period_no__isnull', True), ('placed_date__isnull', True)), models.Q(('period_no__isnull', False), ('placed_date__isnull', False)), _connector='OR'), name='ck_examcalentry_slot_pair'),
        ),
        migrations.AddConstraint(
            model_name='examtrackmark',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('entry', 'item'), name='uq_examtrackmark_alive'),
        ),
    ]
