# Generated by Django 5.1.15 on 2026-08-29 20:49

import django.db.models.deletion
import shared.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0002_schoolconfig_bell_schedule'),
        ('sinav', '0004_examcalendar_examcalendarentry_examtrackitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('teacher_name', shared.crypto.EncryptedCharField(max_length=150, verbose_name='öğretmen adı (snapshot)')),
                ('role', models.CharField(choices=[('PROCTOR', 'Gözetmen'), ('RESERVE', 'Yedek')], default='PROCTOR', max_length=8, verbose_name='rol')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='tebellüğ edildi')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='tebellüğ zamanı')),
                ('room', models.ForeignKey(blank=True, help_text='YEDEK rolünde boş; gözetmende zorunlu (servis doğrular).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proctor_assignments', to='sinav.examroom', verbose_name='salon')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_assignments', to='sinav.examsession', verbose_name='oturum')),
                ('teacher', models.ForeignKey(blank=True, help_text='Anonimleştirilmiş arşivde boş (F27).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proctor_assignments', to='okul.personnel', verbose_name='öğretmen')),
            ],
            options={
                'verbose_name': 'gözetmen görevlendirmesi',
                'verbose_name_plural': 'gözetmen görevlendirmeleri',
                'ordering': ['room_id', 'id'],
                'indexes': [models.Index(fields=['session', 'room'], name='sinav_proctor_sess_room_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('session', 'teacher'), name='uq_proctor_session_teacher_alive'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('role', 'PROCTOR')), fields=('session', 'room'), name='uq_proctor_session_room_proctor_alive')],
            },
        ),
        migrations.CreateModel(
            name='ProctorExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('scope', models.CharField(choices=[('SESSION', 'Oturum'), ('PERMANENT', 'Kalıcı')], default='PERMANENT', max_length=10, verbose_name='kapsam')),
                ('reason_category', models.CharField(choices=[('HEALTH', 'Sağlık'), ('DUTY', 'İdari görev'), ('OTHER', 'Diğer')], default='OTHER', max_length=10, verbose_name='gerekçe kategorisi')),
                ('session', models.ForeignKey(blank=True, help_text='Yalnız SESSION kapsamında dolu.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctor_exemptions', to='sinav.examsession', verbose_name='oturum')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_proctor_exemptions', to='okul.personnel', verbose_name='öğretmen')),
            ],
            options={
                'verbose_name': 'gözetmenlik muafiyeti',
                'verbose_name_plural': 'gözetmenlik muafiyetleri',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('session__isnull', True)), fields=('teacher',), name='uq_proctorexemption_permanent_alive'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('session__isnull', False)), fields=('teacher', 'session'), name='uq_proctorexemption_session_alive')],
            },
        ),
    ]
