# Generated by Django 5.1.15 on 2026-08-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0003_subjectdepartment'),
        ('sinav', '0005_proctorassignment_proctorexemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcalendar',
            name='footnote_text',
            field=models.TextField(blank=True, default='', help_text='Açıklamaların altına basılan kısa not (mazeret sınavı takvimi, okul dışı makam sınavlarının kılavuz tarihleri). Create sırasında varsayılandan kopyalanır.', verbose_name='dipnot'),
        ),
        migrations.AddField(
            model_name='examcalendar',
            name='signatory_departments',
            field=models.ManyToManyField(blank=True, help_text='İmza bloğunda yer alacak zümreler; boşsa takvimdeki derslerden üretilir.', related_name='exam_calendars', to='okul.subjectdepartment', verbose_name='imza zümreleri'),
        ),
        migrations.AddField(
            model_name='examcalendarentry',
            name='authority',
            field=models.CharField(choices=[('SCHOOL', 'Okul'), ('MINISTRY', 'Bakanlık'), ('PROVINCIAL', 'İl MEM'), ('DISTRICT', 'İlçe MEM')], db_index=True, default='SCHOOL', help_text='Okul dışı sınavlarda tarih/saat ilgili makamın kılavuzuna göredir.', max_length=10, verbose_name='hazırlayan makam'),
        ),
    ]
