# Generated by Django 5.1.15 on 2026-08-31 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0006_examcalendar_footnote_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examroom',
            name='block',
            field=models.CharField(blank=True, default='', help_text="Serbest konum bilgisi (örn. 'A Blok 2. Kat'). Salon evrakına BASILIR.", max_length=80, verbose_name='blok / kat'),
        ),
        migrations.CreateModel(
            name='ExamRoomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('name', models.CharField(max_length=60, verbose_name='küme adı')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
            ],
            options={
                'verbose_name': 'derslik kümesi',
                'verbose_name_plural': 'derslik kümeleri',
                'ordering': ['order', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uq_examroomgroup_name_alive')],
            },
        ),
        migrations.AddField(
            model_name='examroom',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Yalnız seçim kolaylığı (ör. Sabah/Öğle); evraka basılmaz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='sinav.examroomgroup', verbose_name='derslik kümesi'),
        ),
    ]
