# Generated by Django 5.1.15 on 2026-08-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0004_classsectiongroup_classsection_group'),
        ('sinav', '0007_alter_examroom_block_examroomgroup_examroom_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementrule',
            name='seat_preference',
            field=models.CharField(choices=[('NONE', 'Fark etmez'), ('FRONT', 'Ön sıra'), ('BACK', 'Arka sıra')], default='NONE', help_text='Koltuk seçilmediğinde salonun hangi ucundan verileceği.', max_length=6, verbose_name='koltuk tercihi'),
        ),
        migrations.AddField(
            model_name='placementrule',
            name='solo_desk',
            field=models.BooleanField(default=False, help_text='Sıradaki diğer koltuklar KİMSEYE verilmez — salon kapasitesi sıra koltuk sayısı kadar (ikili sırada 2) azalır.', verbose_name='tek başına otursun'),
        ),
        migrations.AddField(
            model_name='placementrule',
            name='target_desk_col',
            field=models.PositiveSmallIntegerField(blank=True, help_text='BELIRLI_KOLTUK için zorunlu.', null=True, verbose_name='sıra sütunu'),
        ),
        migrations.AddField(
            model_name='placementrule',
            name='target_desk_row',
            field=models.PositiveSmallIntegerField(blank=True, help_text='BELIRLI_KOLTUK için zorunlu.', null=True, verbose_name='sıra satırı'),
        ),
        migrations.AddField(
            model_name='placementrule',
            name='target_slot',
            field=models.PositiveSmallIntegerField(blank=True, help_text='BELIRLI_KOLTUK için zorunlu.', null=True, verbose_name='sıra içi pozisyon'),
        ),
        migrations.AlterField(
            model_name='placementrule',
            name='rule_type',
            field=models.CharField(choices=[('HOME_CLASSROOM', 'Kendi dersliğinde'), ('FIXED_ROOM', 'Belirli salon'), ('FRONT_ROW', 'Ön sıra'), ('SEPARATE_ROOM', 'Ayrı salon'), ('FIXED_SEAT', 'Belirli koltuk')], max_length=14, verbose_name='kural tipi'),
        ),
        migrations.AddConstraint(
            model_name='placementrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_desk_col__isnull', True), ('target_desk_row__isnull', True), ('target_slot__isnull', True)), models.Q(('target_desk_col__isnull', False), ('target_desk_row__isnull', False), ('target_slot__isnull', False)), _connector='OR'), name='ck_placementrule_seat_triplet'),
        ),
    ]
