# Generated by Django 5.1.15 on 2026-08-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0008_placementrule_seat_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcalendarentry',
            name='participant_type',
            field=models.CharField(choices=[('LEVEL', 'Seviye geneli'), ('SECTIONS', 'Şube şube')], default='LEVEL', help_text='Seviye geneli mi, seçilen şubeler mi (seçmeli derslerde şube kapsamı).', max_length=10, verbose_name='katılımcı tipi'),
        ),
        migrations.AddField(
            model_name='examcalendarentry',
            name='section_ids',
            field=models.JSONField(blank=True, default=list, help_text='SECTIONS tipi için okul.ClassSection id (küme kimliği YAZILMAZ).', verbose_name="şube id'leri"),
        ),
    ]
