# Generated by Django 5.1.15 on 2026-09-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0009_examcalendarentry_participant_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcalendarentry',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='True = otomatik yerleştirme bu girdiyi yerinden oynatmaz.', verbose_name='sabitlenmiş'),
        ),
    ]
