# Generated by Django 5.1.15 on 2026-09-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0010_examcalendarentry_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattendancerecord',
            name='excuse_status',
            field=models.CharField(choices=[('PENDING', 'Beklemede'), ('EXCUSED', 'Mazeretli'), ('UNEXCUSED', 'Mazeretsiz')], db_index=True, default='PENDING', max_length=10, verbose_name='mazeret durumu'),
        ),
    ]
