# Generated by Django 5.1.15 on 2026-09-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0011_mazeret_etiketleri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcalendarentry',
            name='participant_type',
            field=models.CharField(choices=[('LEVEL', 'Sınıf düzeyinin tamamı'), ('SECTIONS', 'Seçili şubeler')], default='LEVEL', help_text='Seviye geneli mi, seçilen şubeler mi (seçmeli derslerde şube kapsamı).', max_length=10, verbose_name='katılımcı tipi'),
        ),
        migrations.AlterField(
            model_name='examsessioncourse',
            name='participant_type',
            field=models.CharField(choices=[('LEVEL', 'Sınıf düzeyinin tamamı'), ('SECTIONS', 'Seçili şubeler')], max_length=10, verbose_name='katılımcı tipi'),
        ),
    ]
