# Generated by Django 5.1.15 on 2026-09-19 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0013_resmi_sinav_haftalari'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattendancerecord',
            name='makeup_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makeup_records', to='sinav.examsessioncourse', verbose_name='mazeret sınavı dersi'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='is_makeup',
            field=models.BooleanField(default=False, verbose_name='mazeret sınavı'),
        ),
        migrations.AlterField(
            model_name='examsessioncourse',
            name='participant_type',
            field=models.CharField(choices=[('LEVEL', 'Sınıf düzeyinin tamamı'), ('SECTIONS', 'Seçili şubeler'), ('MAKEUP', 'Mazeretli öğrenciler')], max_length=10, verbose_name='katılımcı tipi'),
        ),
    ]
