# Generated by Django 5.1.15 on 2026-09-20 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0007_electivereportsection'),
        ('okul', '0009_studentphoto'),
        ('sinav', '0014_mazeret_sinavi'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeupPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('name', models.CharField(max_length=120, verbose_name='takvim adı')),
                ('start_date', models.DateField(verbose_name='başlangıç tarihi')),
                ('day_count', models.PositiveSmallIntegerField(help_text='Hafta içi gün olarak sayılır; hafta sonu atlanır.', verbose_name='gün sayısı')),
                ('max_per_day', models.PositiveSmallIntegerField(default=2, help_text='2 esastır; 3 yalnız zorunlu hâlde (Yönerge md. 5/1-s).', verbose_name='öğrenci başına günlük en çok sınav')),
                ('period_nos', models.JSONField(blank=True, default=list, help_text='Boş = okulun sınav saatleri (Ayarlar → Ders saatleri).', verbose_name='sınav ders saatleri')),
                ('strict_order', models.BooleanField(default=True, verbose_name='asıl takvim sırası kesin korunur')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('APPROVED', 'Onaylandı')], db_index=True, default='DRAFT', max_length=12, verbose_name='durum')),
                ('approved_by_name', models.CharField(blank=True, default='', max_length=128, verbose_name='onaylayan')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='onay zamanı')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='makeup_plans', to='okul.schoolterm', verbose_name='dönem')),
            ],
            options={
                'verbose_name': 'mazeret sınav takvimi',
                'verbose_name_plural': 'mazeret sınav takvimleri',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MakeupPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('level', models.PositiveSmallIntegerField(verbose_name='sınıf düzeyi')),
                ('source_date', models.DateField(verbose_name='asıl sınav tarihi')),
                ('source_time', models.TimeField(verbose_name='asıl sınav saati')),
                ('external', models.BooleanField(default=False, verbose_name='üst makam sınavı')),
                ('placed_date', models.DateField(blank=True, null=True, verbose_name='mazeret sınavı tarihi')),
                ('period_no', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ders saati')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='sabit')),
                ('note', models.CharField(blank=True, default='', max_length=400, verbose_name='yerleşmeme gerekçesi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dersler.course', verbose_name='ders')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sinav.makeupplan', verbose_name='takvim')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makeup_plan_items', to='sinav.examsession', verbose_name='mazeret oturumu')),
            ],
            options={
                'verbose_name': 'mazeret takvimi sınavı',
                'verbose_name_plural': 'mazeret takvimi sınavları',
                'ordering': ['source_date', 'source_time', 'id'],
            },
        ),
        migrations.AddField(
            model_name='examattendancerecord',
            name='makeup_plan_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='sinav.makeupplanitem', verbose_name='mazeret takvimi sınavı'),
        ),
        migrations.AddConstraint(
            model_name='makeupplanitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('plan', 'course', 'level'), name='uq_makeupplanitem_plan_course_level_alive'),
        ),
    ]
