# Generated by Django 5.1.15 on 2026-09-20 07:53

import django.db.models.deletion
import shared.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0015_mazeret_takvimi'),
    ]

    operations = [
        migrations.CreateModel(
            name='IepStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('student_ref', shared.crypto.EncryptedCharField(max_length=20, verbose_name='BEP kapsamındaki öğrenci')),
            ],
            options={
                'verbose_name': 'BEP kapsamındaki öğrenci',
                'verbose_name_plural': 'BEP kapsamındaki öğrenciler',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='examsession',
            name='individual_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='bireysel soru dosyası değişim zamanı'),
        ),
        migrations.CreateModel(
            name='IndividualQuestionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('student_ref', shared.crypto.EncryptedCharField(max_length=20, verbose_name='bireysel soru dosyası öğrencisi')),
                ('file', models.FileField(blank=True, upload_to='exam_questions/%Y/%m/', verbose_name="bireysel soru PDF'i")),
                ('page_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='sayfa sayısı')),
                ('sha256', models.CharField(blank=True, default='', max_length=64, verbose_name='içerik özeti')),
                ('score_mode', models.CharField(choices=[('SINGLE_BOX', 'Tek puan kutusu'), ('QUESTION_TABLE', 'Soru bazlı puan tablosu')], default='SINGLE_BOX', max_length=14, verbose_name='puan bölümü')),
                ('question_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='soru sayısı')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_questions', to='sinav.examsession', verbose_name='oturum')),
            ],
            options={
                'verbose_name': 'bireysel soru dosyası',
                'verbose_name_plural': 'bireysel soru dosyaları',
                'ordering': ['pk'],
            },
        ),
    ]
