# Generated by Django 5.1.15 on 2026-09-20 12:30

import shared.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0016_bep_bireysel_soru_dosyasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='separation_mode',
            field=models.CharField(choices=[('NONE', 'Kapalı'), ('DESK', 'Aynı sıraya oturtma'), ('ROOM', 'Ayrı salonlar')], default='NONE', max_length=8, verbose_name='kız/erkek ayrışması'),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='separation_key',
            field=shared.crypto.EncryptedCharField(blank=True, default='', max_length=1, verbose_name='ayrışma anahtarı (snapshot)'),
        ),
    ]
