# Generated by Django 5.1.15 on 2026-09-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0017_separation'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcalendar',
            name='print_period_times',
            field=models.BooleanField(default=True, help_text="Kapalıyken evrakta yalnız ders saati adı basılır (ör. '3. Ders').", verbose_name='saatleri yazdır'),
        ),
    ]
