# Generated by Django 5.1.15 on 2026-10-07 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0018_examcalendar_print_period_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='iepstudent',
            name='extra_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = ek süre yok.', verbose_name='ek süre (dakika)'),
        ),
        migrations.AddField(
            model_name='iepstudent',
            name='placement',
            field=models.CharField(choices=[('NONE', 'Yer kuralı yok'), ('HOME_CLASSROOM', 'Kendi sınıfında'), ('SEPARATE_ROOM', 'Ayrı salon'), ('FRONT_ROW', 'Ön sırada')], default='NONE', max_length=14, verbose_name='yer'),
        ),
        migrations.AddField(
            model_name='iepstudent',
            name='reader',
            field=models.BooleanField(default=False, verbose_name='okuyucu desteği'),
        ),
        migrations.AddField(
            model_name='iepstudent',
            name='reason_category',
            field=models.CharField(choices=[('DISABILITY', 'Engel durumu'), ('IEP', 'BEP'), ('HEALTH', 'Sağlık'), ('OTHER', 'Diğer')], default='IEP', help_text='Yalnız kategori — tanı/rapor bilgisi ASLA tutulmaz.', max_length=10, verbose_name='gerekçe'),
        ),
        migrations.AddField(
            model_name='iepstudent',
            name='scribe',
            field=models.BooleanField(default=False, verbose_name='yazıcı desteği'),
        ),
        migrations.AddField(
            model_name='iepstudent',
            name='seat_preference',
            field=models.CharField(choices=[('NONE', 'Fark etmez'), ('FRONT', 'Ön sıra'), ('BACK', 'Arka sıra')], default='NONE', max_length=6, verbose_name='salon içinde'),
        ),
        migrations.AddField(
            model_name='iepstudent',
            name='solo_desk',
            field=models.BooleanField(default=False, verbose_name='sırada tek başına'),
        ),
        migrations.AddField(
            model_name='iepstudent',
            name='target_room',
            field=models.ForeignKey(blank=True, help_text='Yalnız “Ayrı salon” yerinde dolu.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accommodations', to='sinav.examroom', verbose_name='ayrı salon'),
        ),
    ]
