#!/bin/sh
# Kelebek Sınav - kaldirma oncesi.
# KULLANICI VERISI SILINMEZ: veritabani, yedekler ve gunlukler
# ~/.local/share/kelebek-sinav altindadir; paket yalnizca program
# dosyalarini kaldirir. (ASCII: bkz. postinst basindaki not.)
set -e

exit 0
