# Generated by Django 5.1.15 on 2026-08-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('name', models.CharField(db_index=True, help_text="Örn. 'Türk Dili ve Edebiyatı', 'Seçmeli İngilizce'.", max_length=120, verbose_name='ders adı')),
                ('levels', models.JSONField(default=list, help_text='Dersin okutulduğu sınıf düzeyleri, artan sıralı liste (örn. [9, 10]).', verbose_name='seviyeler')),
                ('course_type', models.CharField(choices=[('COMMON', 'Ortak'), ('ELECTIVE', 'Seçmeli')], default='COMMON', max_length=10, verbose_name='tür')),
                ('source', models.CharField(choices=[('MEB_CATALOG', 'MEB çizelgesi'), ('MANUAL', 'Elle giriş')], default='MANUAL', help_text="MEB çizelge import'u dokunduğu kaydı MEB_CATALOG olarak işaretler.", max_length=12, verbose_name='kaynak')),
                ('is_active', models.BooleanField(default=True, help_text='Pasif ders yeni planlamada seçilemez; kayıt silinmez.', verbose_name='aktif')),
            ],
            options={
                'verbose_name': 'ders',
                'verbose_name_plural': 'dersler',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uq_course_name_alive')],
            },
        ),
        migrations.CreateModel(
            name='CourseAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('alias_key', models.CharField(db_index=True, help_text='Normalize edilmiş takma ad (course_match_key çıktısı).', max_length=200, verbose_name='takma ad anahtarı')),
                ('display_name', models.CharField(help_text="Listede görüldüğü haliyle takma ad (örn. 'Din Kül. ve Ah. Bil.').", max_length=200, verbose_name='takma ad (görünen)')),
                ('source', models.CharField(choices=[('OPERATOR', 'Operatör (birleştirme öğrenmesi)'), ('SEED', 'Seed listesi')], default='OPERATOR', max_length=10, verbose_name='kaynak')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='dersler.course', verbose_name='kanonik ders')),
            ],
            options={
                'verbose_name': 'ders takma adı',
                'verbose_name_plural': 'ders takma adları',
                'ordering': ['alias_key'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('alias_key',), name='uq_course_alias_key_alive')],
            },
        ),
    ]
