# Generated by Django 5.1.15 on 2026-08-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_mode',
            field=models.CharField(choices=[('WRITTEN', 'Yazılı'), ('PRACTICE', 'Uygulama'), ('NONE', 'Sınav yok')], default='WRITTEN', help_text="Takvim havuzunun otomatik doldurulması yalnız 'Yazılı' dersleri alır; 'Uygulama' ve 'Sınav yok' dersleri gerekirse elle eklenir.", max_length=10, verbose_name='sınav biçimi'),
        ),
    ]
