# Generated by Django 5.1.15 on 2026-09-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0003_course_exam_mode_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='catalog_excluded',
            field=models.BooleanField(default=False, help_text='Okulun yürürlükteki MEB çizelgesinde yok; senkron pasifleştirdi.', verbose_name='çizelge dışı'),
        ),
    ]
