# Generated by Django 5.1.15 on 2026-09-03 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0004_okul_turu_cizelgeleri'),
        ('okul', '0006_schoolconfig_daily_period_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSectionOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('level', models.PositiveSmallIntegerField(help_text='Sınıf düzeyi (0=Hazırlık, 9-12).', verbose_name='seviye')),
                ('section_ids', models.JSONField(blank=True, default=list, help_text='okul.ClassSection id listesi (küme kimliği YAZILMAZ).', verbose_name="şube id'leri")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_offerings', to='dersler.course', verbose_name='ders')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_section_offerings', to='okul.schoolyear', verbose_name='ders yılı')),
            ],
            options={
                'verbose_name': 'ders şube kapsamı',
                'verbose_name_plural': 'ders şube kapsamları',
                'ordering': ['course', 'level'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('course', 'school_year', 'level'), name='uq_course_offering_alive')],
            },
        ),
    ]
