# Generated by Django 5.1.15 on 2026-09-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0005_coursesectionoffering'),
        ('okul', '0008_alter_importrun_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='dersler.course', verbose_name='ders')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='okul.schoolyear', verbose_name='ders yılı')),
                ('section', models.ForeignKey(help_text='Öğrencinin listeye girdiği andaki şubesi; şube değişirse satır düşer.', on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='okul.classsection', verbose_name='şube')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='okul.student', verbose_name='öğrenci')),
            ],
            options={
                'verbose_name': 'ders öğrencisi',
                'verbose_name_plural': 'ders öğrencileri',
                'ordering': ['course', 'section', 'student'],
                'indexes': [models.Index(fields=['school_year', 'course', 'section'], name='dersler_enroll_lookup_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('course', 'school_year', 'student'), name='uq_course_enrollment_alive')],
            },
        ),
    ]
