# Generated by Django 5.1.15 on 2026-09-19 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0006_courseenrollment'),
        ('okul', '0008_alter_importrun_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_report_sections', to='okul.schoolyear', verbose_name='ders yılı')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_report_sections', to='okul.classsection', verbose_name='şube')),
            ],
            options={
                'verbose_name': 'seçmeli raporu kapsamı',
                'verbose_name_plural': 'seçmeli raporu kapsamları',
                'ordering': ['school_year', 'section'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('school_year', 'section'), name='uq_elective_report_section_alive')],
            },
        ),
    ]
