# Generated by Django 5.1.15 on 2026-10-07 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0007_electivereportsection'),
        ('okul', '0013_classsection_shift_schoolconfig_afternoon_bell_flow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingElectiveChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('previous_course_ids', models.JSONField(blank=True, default=list, help_text='Dersler.Course id listesi — pencerenin önerisi.', verbose_name='eski şubedeki seçmeliler')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_elective_choices', to='okul.schoolyear', verbose_name='ders yılı')),
                ('section', models.ForeignKey(help_text='Seçimin beklendiği şube — öğrencinin satır yazıldığı andaki şubesi.', on_delete=django.db.models.deletion.CASCADE, related_name='pending_elective_choices', to='okul.classsection', verbose_name='şube')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_elective_choices', to='okul.student', verbose_name='öğrenci')),
            ],
            options={
                'verbose_name': 'seçmeli ders seçimi bekleyen öğrenci',
                'verbose_name_plural': 'seçmeli ders seçimi bekleyen öğrenciler',
                'ordering': ['section', 'student'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('student', 'school_year'), name='uq_pending_elective_choice_alive')],
            },
        ),
    ]
